kafkaServer:
  - kafka:9092

env:
  - name: KAFKA_USERNAME
    value: admin
  - name: KAFKA_PASSWORD
    value: kafka

prometheus:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: "30s"
    additionalLabels:
      release: kube-prometheus-stack

requests: {}

sasl:
  enabled: true
  handshake: true
  scram:
    enabled: true
    mechanism: plain
    username: admin
    password: kafka
