listeners:
  client:
    name: CLIENT
    containerPort: 9092
    protocol: SASL_PLAINTEXT
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: SASL_PLAINTEXT
  interbroker:
    name: INTERNAL
    containerPort: 9094
    protocol: SASL_PLAINTEXT
  external:
    name: EXTERNAL
    containerPort: 9095
    protocol: SASL_PLAINTEXT
    sasl:
      enabledMechanisms: PLAIN

sasl:
  enabledMechanisms: PLAIN
  interBrokerMechanism: PLAIN
  controllerMechanism: PLAIN
  client:
    users:
      - admin
    passwords: kafka

controller:
  replicaCount: 1
  heapOpts: -Xmx1024m -Xms1024m

  resources: {}
    # requests:
    #   cpu: 500m
    #   memory: 512Mi
    # limits:
    #   cpu: 1
    #   memory: 1024Mi
  
  persistence:
    enabled: true
    size: 1Gi
  
# metrics:
#   jmx:
#     enabled: true
#   serviceMonitor:
#     enabled: true
#     interval: "30s"
#     labels:
#       release: kube-prometheus-stack