master:
  persistence:
    enabled: true
    size: 100Mi
  resources: {}

replica:
  replicaCount: 1
  persistence:
    enabled: true
    size: 100Mi
  resources: {}

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    additionalLabels:
      release: kube-prometheus-stack